[workspace]
authors = [
    "Jean-Yves Tinevez <tinevez@pasteur.fr>",
	"Gaelle Letort",
]
channels = ["conda-forge"]
name = "yolo-appose"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10.3,<3.13"
packaging = ">=26.2,<27"
wheel = "*"
hatchling = "*"
cmake = "*"

[pypi-dependencies]
appose = ">=0.10.1, <0.13"

# --- PyTorch features ---
# See for more details on torch versions and CUDA support: https://pytorch.org/get-started/previous-versions/
# macOS does not support CUDA and will always fall back to CPU.

# CPU: all platforms use the CPU index
[feature.cpu.target.linux.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

[feature.cpu.target.win.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

[feature.cpu.target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# Deprecated: osx-64 support should be drop in favor of osx-arm64
[feature.cpu.target.osx-64.pypi-dependencies]
torch = { version = ">=2.2.2, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.17.2, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# CUDA 12.6: Linux/Windows use cu126 index, macOS falls back to CPU
[feature.cu126.target.linux.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu126" }

[feature.cu126.target.win.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu126" }

[feature.cu126.target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# Deprecated: osx-64 support should be drop in favor of osx-arm64
[feature.cu126.target.osx-64.pypi-dependencies]
torch = { version = ">=2.2.2, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.17.2, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# CUDA 13.0: Linux/Windows use cu130 index, macOS falls back to CPU
[feature.cu130.target.linux.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu130" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu130" }

[feature.cu130.target.win.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu130" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu130" }

[feature.cu130.target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# Deprecated: osx-64 support should be drop in favor of osx-arm64
[feature.cu130.target.osx-64.pypi-dependencies]
torch = { version = ">=2.2.2, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.17.2, <0.26", index = "https://download.pytorch.org/whl/cpu" }


[feature.yolo.pypi-dependencies]
ultralytics = ">=8.3, <9"

# --- Environments ---
## See if it s necessary to handle the torch versions and add cu130 like in cellpose
[environments]
default  = { features = ["yolo"] }
yolo-cpu  = { features = ["yolo", "cpu"] }
yolo-gpu  = { features = ["yolo", "cu126"] }
